
[package]
name = "mineshaft-legacy"
version = "0.1.0"
edition = "2024"

[dependencies]
mineshaft-server = { workspace = true }
raknet = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
socket2 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
byteorder = { workspace = true }
rand = { workspace = true }
